# -*- coding: utf-8 -*-

EN_STOPWORDS = {
    "the", "a", "an", "is", "are", "was", "were", "to", "of", "in", "on",
    "and", "or", "for", "with", "as", "by", "from", "at", "that", "this",
    "it", "they", "we", "you", "he", "she", "them", "us", "him", "her",
    "his", "hers", "its", "my", "your", "our", "their", "myself", "yourself",
    "himself", "herself", "itself", "ourselves", "yourselves", "themselves",
    "what", "which", "who", "whom", "this", "that", "these", "those", "am",
    "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
    "having", "do", "does", "did", "doing", "but", "if", "or", "because",
    "while", "where", "when", "how", "all", "any", "both", "each", "few",
    "more", "most", "other", "some", "such", "no", "nor", "not", "only",
    "own", "same", "so", "than", "too", "very", "can", "will", "just",
    "should", "now", "i", "me", "my", "we", "us", "our", "ours"
}

EN_CONTRACTIONS = {
    "don't": "do not",
    "can't": "can not",
    "won't": "will not",
    "i'm": "i am",
    "it's": "it is",
    "you're": "you are",
    "they're": "they are",
    "we're": "we are",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "didn't": "did not",
    "doesn't": "does not",
    "haven't": "have not",
    "hasn't": "has not",
    "hadn't": "had not",
    "couldn't": "could not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "mightn't": "might not",
    "mustn't": "must not",
    "let's": "let us",
    "there's": "there is",
    "here's": "here is",
    "what's": "what is",
    "where's": "where is",
    "when's": "when is",
    "why's": "why is",
    "how's": "how is",
    "who's": "who is",
    "i've": "i have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "i would",
    "you'd": "you would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "i will",
    "you'll": "you will",
    "we'll": "we will",
    "they'll": "they will",
    "that's": "that is",
    "there're": "there are",
    "here're": "here are",
    "what're": "what are",
    "where're": "where are",
    "when're": "when are",
    "why're": "why are",
    "how're": "how are",
    "who're": "who are",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "ma'am": "madam",
    "o'clock": "of the clock"
}
