# -*- coding: utf-8 -*-

DE_STOPWORDS = {
    "der", "die", "das", "den", "dem", "des", "ein", "eine", "einer", "eines",
    "einem", "einen", "kein", "keine", "keiner", "keines", "keinem", "keinen",
    "ist", "sind", "war", "waren", "hat", "haben", "hatte", "hatten", "wird",
    "werden", "wurde", "wurden", "kann", "können", "konnte", "konnten", "muss",
    "müssen", "musste", "mussten", "soll", "sollen", "sollte", "sollten", "mag",
    "mögen", "mochte", "mochten", "ich", "du", "er", "sie", "es", "wir", "ihr",
    "sie", "mich", "dich", "ihn", "ihn", "uns", "euch", "sie", "mir", "dir",
    "ihm", "ihr", "ihnen", "mein", "dein", "sein", "ihr", "unser", "euer",
    "ihr", "meine", "deine", "seine", "ihre", "unsere", "eure", "ihre",
    "meinen", "deinen", "seinen", "ihren", "unseren", "euren", "ihren",
    "meinem", "deinem", "seinem", "ihrem", "unserem", "eurem", "ihrem",
    "meines", "deines", "seines", "ihres", "unseres", "eures", "ihres",
    "meiner", "deiner", "seiner", "ihrer", "unserer", "eurer", "ihrer",
    "meins", "deins", "seins", "ihrs", "unseres", "eures", "ihrs",
    "nicht", "auch", "so", "wie", "nur", "noch", "schon", "immer", "wieder",
    "aber", "oder", "und", "weil", "wenn", "ob", "bis", "da", "wo", "wie",
    "als", "während", "seit", "nach", "vor", "bei", "zu", "von", "aus", "mit",
    "durch", "für", "ohne", "gegen", "über", "unter", "zwischen", "neben",
    "hinter", "vor", "auf", "in", "an", "bei", "dies", "diese", "dieser",
    "dieses", "diesen", "diesem", "jener", "jene", "jenes", "jenen", "jenem",
    "man", "einer", "niemand", "jemand", "alle", "allem", "allen", "aller",
    "alles", "andere", "anderem", "anderen", "anderer", "anderes", "beide",
    "beidem", "beiden", "beider", "beides", "einige", "einigem", "einigen",
    "einiger", "einiges", "etwas", "wenig", "wenige", "wenigem", "wenigen",
    "weniger", "weniges", "viel", "viele", "vielem", "vielen", "vieler",
    "vieles", "selbst", "sich", "hier", "dort", "da", "hin", "her", "dann",
    "nun", "jetzt", "bald", "früher", "später", "heute", "morgen", "gestern",
    "ja", "nein", "doch", "mal", "eben", "gerade", "schon", "wohl", "auch",
    "nur", "noch", "zwar", "zudem", "außerdem", "deshalb", "daher", "darum",
    "somit", "also", "denn", "jedoch", "doch", "sondern", "entweder", "oder",
    "weder", "noch", "sowohl", "als", "nicht", "nur", "sondern", "auch",
    "sowohl", "wie", "weder", "noch", "entweder", "oder", "einerseits",
    "andererseits", "deshalb", "darum", "deshalb", "aus diesem grund",
    "aus diesem grunde", "deshalb", "darum", "aus diesem grund",
    "aus diesem grunde", "deshalb", "darum"
}
