# -*- coding: utf-8 -*-

DE_STOPWORDS = {
    "der", "die", "das", "den", "dem", "des", "ein", "eine", "einer", "eines",
    "einem", "einen", "kein", "keine", "keiner", "keines", "keinem", "keinen",
    "ist", "sind", "war", "waren", "hat", "haben", "hatte", "hatten", "wird",
    "werden", "wurde", "wurden", "kann", "können", "konnte", "konnten", "muss",
    "müssen", "musste", "mussten", "soll", "sollen", "sollte", "sollten", "mag",
    "mögen", "mochte", "mochten", "ich", "du", "er", "sie", "es", "wir", "ihr",
    "sie", "mich", "dich", "ihn", "ihn", "uns", "euch", "sie", "mir", "dir",
    "ihm", "ihr", "ihnen", "mein", "dein", "sein", "ihr", "unser", "euer",
    "ihr", "meine", "deine", "seine", "ihre", "unsere", "eure", "ihre",
    "meinen", "deinen", "seinen", "ihren", "unseren", "euren", "ihren",
    "meinem", "deinem", "seinem", "ihrem", "unserem", "eurem", "ihrem",
    "meines", "deines", "seines", "ihres", "unseres", "eures", "ihres",
    "meiner", "deiner", "seiner", "ihrer", "unserer", "eurer", "ihrer",
    "meins", "deins", "seins", "ihrs", "unseres", "eures", "ihrs",
    "nicht", "auch", "so", "wie", "nur", "noch", "schon", "immer", "wieder",
    "aber", "oder", "und", "weil", "wenn", "ob", "bis", "da", "wo", "wie",
    "als", "während", "seit", "nach", "vor", "bei", "zu", "von", "aus", "mit",
    "durch", "für", "ohne", "gegen", "über", "unter", "zwischen", "neben",
    "hinter", "vor", "auf", "in", "an", "bei", "dies", "diese", "dieser",
    "dieses", "diesen", "diesem", "jener", "jene", "jenes", "jenen", "jenem",
    "man", "einer", "niemand", "jemand", "alle", "allem", "allen", "aller",
    "alles", "andere", "anderem", "anderen", "anderer", "anderes", "beide",
    "beidem", "beiden", "beider", "beides", "einige", "einigem", "einigen",
    "einiger", "einiges", "etwas", "wenig", "wenige", "wenigem", "wenigen",
    "weniger", "weniges", "viel", "viele", "vielem", "vielen", "vieler",
    "vieles", "selbst", "sich", "hier", "dort", "da", "hin", "her", "dann",
    "nun", "jetzt", "bald", "früher", "später", "heute", "morgen", "gestern",
    "ja", "nein", "doch", "mal", "eben", "gerade", "schon", "wohl", "auch",
    "nur", "noch", "zwar", "zudem", "außerdem", "deshalb", "daher", "darum",
    "somit", "also", "denn", "jedoch", "doch", "sondern", "entweder", "oder",
    "weder", "noch", "sowohl", "als", "nicht", "nur", "sondern", "auch",
    "sowohl", "wie", "weder", "noch", "entweder", "oder", "einerseits",
    "andererseits", "deshalb", "darum", "deshalb", "aus diesem grund",
    "aus diesem grunde", "deshalb", "darum", "aus diesem grund",
    "aus diesem grunde", "deshalb", "darum"
}

DE_CONTRACTIONS = {
    "hab'n": "haben",
    "bin's": "bin es",
    "bist's": "bist es",
    "ist's": "ist es",
    "sind's": "sind es",
    "war's": "war es",
    "waren's": "waren es",
    "kann's": "kann es",
    "kannst's": "kannst es",
    "können's": "können es",
    "musst's": "musst es",
    "muss's": "muss es",
    "müssen's": "müssen es",
    "will's": "will es",
    "willst's": "willst es",
    "wollen's": "wollen es",
    "soll's": "soll es",
    "sollst's": "sollst es",
    "sollen's": "sollen es",
    "mag's": "mag es",
    "magst's": "magst es",
    "mögen's": "mögen es",
    "geht's": "geht es",
    "gibt's": "gibt es",
    "macht's": "macht es",
    "sieht's": "sieht es",
    "hör's": "hör es",
    "hörst's": "hörst es",
    "hört's": "hört es",
    "komm's": "komm es",
    "kommst's": "kommst es",
    "kommt's": "kommt es",
    "wird's": "wird es",
    "werden's": "werden es",
    "hätt's": "hätte es",
    "hättest's": "hättest es",
    "hätte's": "hätte es",
    "hätten's": "hätten es",
    "wär's": "wäre es",
    "wärst's": "wärst es",
    "wären's": "wären es",
    "dafür": "da für",
    "daran": "da an",
    "darüber": "da über",
    "dabei": "da bei",
    "damit": "da mit",
    "davor": "da vor",
    "dahinter": "da hinter",
    "daneben": "da neben",
    "darin": "da in",
    "darum": "da um",
    "darauf": "da auf",
    "durch's": "durch das",
    "für's": "für das",
    "über's": "über das",
    "um's": "um das",
    "gegen's": "gegen das",
    "ohne's": "ohne das",
    "am": "an dem",
    "ans": "an das",
    "beim": "bei dem",
    "im": "in dem",
    "ins": "in das",
    "zum": "zu dem",
    "zur": "zu der",
    "vom": "von dem",
    "hinter'm": "hinter dem",
    "über'm": "über dem",
    "unter'm": "unter dem",
    "neben'm": "neben dem",
    "vor'm": "vor dem",
    "auf'm": "auf dem",
    "in's": "in das",
    "auf's": "auf das",
    "an's": "an das",
    "weg's": "weg es",
    "rein's": "rein es",
    "raus's": "raus es",
    "daheim's": "daheim es",
    "allein's": "allein es",
    "zusammen's": "zusammen es",
    "nochmal's": "nochmal es",
    "wieder's": "wieder es",
    "schon's": "schon es",
    "jetzt's": "jetzt es",
    "gleich's": "gleich es",
    "einfach's": "einfach es",
    "wirklich's": "wirklich es",
    "sicher's": "sicher es",
    "klar's": "klar es",
    "natürlich's": "natürlich es",
    "ja's": "ja es",
    "nein's": "nein es",
    "doch's": "doch es",
    "mal's": "mal es",
    "eben's": "eben es",
    "gerade's": "gerade es",
    "wohl's": "wohl es",
    "auch's": "auch es",
    "nur's": "nur es",
    "noch's": "noch es",
    "zwar's": "zwar es",
    "außerdem's": "außerdem es",
    "deshalb's": "deshalb es",
    "daher's": "daher es",
    "somit's": "somit es",
    "also's": "also es",
    "denn's": "denn es",
    "jedoch's": "jedoch es",
    "sondern's": "sondern es",
    "entweder's": "entweder es",
    "oder's": "oder es",
    "weder's": "weder es",
    "sowohl's": "sowohl es",
    "als's": "als es",
    "wie's": "wie es",
    "nicht's": "nicht es",
    "einerseits's": "einerseits es",
    "andererseits's": "andererseits es",
    "aus diesem grund's": "aus diesem grund es",
    "aus diesem grunde's": "aus diesem grunde es"
}
